version: 0.2
env:
  parameter-store:
    DOCKERHUB_USERNAME: DOCKERHUB_USERNAME
    DOCKERHUB_PASS: DOCKERHUB_PASSWORD
phases:
  install:
    commands:
      - apt-get update
      - apt install docker.io -y
  pre_build:
    commands:
      - echo Logging in to the DockerHub.....
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      - echo Logging in to Amazon ECR.....
      - aws ecr get-login-password --region us-east-2 | sudo docker login --username aws --password-stdin 194792336910.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Building the Backend Docker image...
      - cd services/backend/
      - docker build -t musicdome-repo_backend -f Dockerfile-prod .
  post_build:
    commands:
      - echo Renaming the Backend Docker image...
      - docker tag musicdome-repo_backend 194792336910.dkr.ecr.us-east-1.amazonaws.com/musicdome-repo_backend:latest
      - echo Pushing the Backend Docker image to ECR...
      - docker push 194792336910.dkr.ecr.us-east-1.amazonaws.com/musicdome-repo_backend:latest
