version: '3'
services:
  backend:
    build: ./services/backend/backend
    ports:
      - 8000:8000
    volumes:
      - ./services/backend/backend:/backend
    command: python manage.py runserver 0.0.0.0:8000
