# Generated by Django 4.1 on 2022-11-03 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=500)),
                ("release_year", models.CharField(max_length=10)),
                ("cover_image", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("musicbrainz_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "_id",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=500)),
                ("playback_duration", models.FloatField()),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="musicdome.album",
                    ),
                ),
                ("artists", models.ManyToManyField(to="musicdome.artist")),
                ("genres", models.ManyToManyField(to="musicdome.genre")),
            ],
        ),
    ]
